### PR TITLE
Backend: Set field.Config.DisplayNameFromDS instead of frame.name

### LINKED ISSUE #178: Backend: Time series legend is duplicating
**What happened**:
While working on this PR https://github.com/grafana/opensearch-datasource/pull/168,  noticed this the legend had duplicated labels:
Screenshot 2023-05-12 at 16 42 45

**What you expected to happen**:
The legend should only the label once

**How to reproduce it (as minimally and precisely as possible)**:
- Set OpenSearch datasource
- Set Average metric on field / Date Histogram on A
- Add metric "derivative" on Average metric
- Add Expression `$A`
- Observe the duplicated labels

**Anything else we need to know?**:
Thank you @idastambuk for the pointer on how to resolve the issue
Resolution will be similar to https://github.com/grafana/grafana/pull/66039
Will also use the changes from https://github.com/grafana/grafana/pull/60169 

**Environment**:
- Grafana version:
- Plugin version:

### PR DESCRIPTION
**Pull request by fridgepoet**
**What this PR does / why we need it**:

The time series legend when displayed from a backend query (alerting, expressions) was duplicating.

This PR applies a [change from Elasticsearch](https://github.com/grafana/grafana/pull/60169) to generate field names for the value field of time series frames. 

It applies the fixes from [another PR in Elasticsearch ](https://github.com/grafana/grafana/pull/66039) to move from putting the frame name in `frame.name` to `field.Config.DisplayNameFromDS` and getting the metric name from `metric.Field` instead of `metric.ID`. 

The screenshot illustrates the same label for a backend flow and frontend flow. 
Screenshot 2023-05-22 at 18 48 19

Thank you @idastambuk for pointing out where to set the legend.

**Which issue(s) this PR fixes**:

Fixes #178

### CODE REVIEW

File: pkg/opensearch/response_parser.go [hunk 1]
```diff
@@ -183,30 +183,27 @@ func (rp *responseParser) processMetrics(esAgg *simplejson.Json, target *Query,
...
-			valueField.Labels = data.Labels{}
-
-			for i, v := range buckets {
+			labels := make(map[string]string, len(props))
+			timeVector := make([]*time.Time, 0, len(buckets))
+			values := make([]*float64, 0, len(buckets))
+
+			for _, v := range buckets {
 				bucket := utils.NewJsonFromAny(v)
-				value := castToNullFloat(bucket.Get("doc_count"))
```
Comment (sarahzinger) [inline pkg/opensearch/response_parser.go:199]: is there any diff between castToNullFloat and castToFloat?

**Review by kevinwcyu — APPROVED** [review]
