### PR TITLE
Fix flaky tests

### LINKED ISSUE #368: Fix flaky node graph tests
**What happened**:
Two of the node graph tests added in [test 1](https://github.com/grafana/opensearch-datasource/blob/8b2f845fe03cd6d9f3c20e42ebd0227552a2a4e4/pkg/opensearch/response_parser_test.go#L2667) and [test 2](https://github.com/grafana/opensearch-datasource/blob/8b2f845fe03cd6d9f3c20e42ebd0227552a2a4e4/pkg/opensearch/opensearch_test.go#L39) are flaky due to the map used by backend.Response.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- OpenSearch version:
- Plugin version:

### PR DESCRIPTION
**Pull request by iwysiu**
**What this PR does / why we need it**:
Due to backend.Responses being a map, we end up getting the services/operations in an inconsistent order when we have multiple responses. This makes some of the tests flaky ([test 1](https://github.com/grafana/opensearch-datasource/blob/8b2f845fe03cd6d9f3c20e42ebd0227552a2a4e4/pkg/opensearch/response_parser_test.go#L2667) and [test 2](https://github.com/grafana/opensearch-datasource/blob/8b2f845fe03cd6d9f3c20e42ebd0227552a2a4e4/pkg/opensearch/opensearch_test.go#L39)). One fix for that is just sorting the operations and services (done in this pr), though if we think that's too expensive (I don't think we should have that many of them?) we could also try to rework the tests, though considering that one of them involves checking a big json string that could either be a bit complex or just involve not using 2 responses (though that reduces the test coverage).

The other change was to avoid a seg fault in `TestProcessTraceListAndTraceSpansResponse`, which was happening because the helper that generated the test queries used a map and was unordered. Changed to an array.

**Which issue(s) this PR fixes**:

Fixes #368 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/opensearch/response_parser_test.go [hunk 1]
```diff
@@ -17,15 +17,20 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
-func createDataQueriesForTests(tsdbQueries map[string]string) []backend.DataQuery {
+type tsdbQuery struct {
+	refId string
+	body  string
+}
+
+func createDataQueriesForTests(tsdbQueries []tsdbQuery) []backend.DataQuery {
```
Comment (iwysiu) [inline pkg/opensearch/response_parser_test.go:25]: Alternatively I could create a second helper that takes an array, but the map sort of implies that it should take multiple queries.

File: pkg/opensearch/response_parser_test.go [hunk 2]
```diff
@@ -2831,53 +2879,49 @@ func TestProcessTraceListAndTraceSpansResponse(t *testing.T) {
...
-								},
-								"traceGroup": "HTTP GET /dispatch",
-								"serviceName": "frontend",
-								"parentSpanId": "",
-								"spanId": "47ed3a25a7dba0cd",
-								"traceState": "",
-								"name": "HTTP GET /dispatch",
-								"startTime": "2023-10-18T07:58:37.818589Z",
-								"links": [],
+			}
```
Comment (iwysiu) [inline pkg/opensearch/response_parser_test.go:2882]: I just changed the indents on this to be easier to read.

File: pkg/opensearch/lucene_handler.go [hunk 3]
```diff
@@ -309,10 +310,12 @@ func getParametersFromServiceMapResult(smResult *client.SearchResponse) ([]strin
 			}
 		}
 	}
+
 	operations := make([]string, 0, len(operationMap))
 	for op := range operationMap {
 		operations = append(operations, op)
 	}
+	slices.Sort(operations)
```
Comment (sarahzinger) [inline pkg/opensearch/lucene_handler.go:318]: I feel like if sorting the operations benefitted users in someway it might make sense to do this, but if I understand correctly this is always going to be rendered as a graph where sorting won't really matter. I would vote we try sorting in the test if that's possible?
